### ISSUE TITLE
Error: Cannot find module 'markov'

### ISSUE THREAD

**Issue by nylki** [b3nj4m/node-markov#1]
Hey there,
Just cloned _node-markov_ and wanted to try the example. I am getting this error:

``` .js
➜  node-markov git:(master) node example/qwantz.js
module.js:336
    throw err;
          ^
Error: Cannot find module 'markov'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/tom/gits/node-markov/example/qwantz.js:4:14)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)

```

**Comment by mk-pmb** [comment]
Try naming the repo directory `markov` and its parent directory `node_modules`. Or you could make a subdirectory `node_modules` and put a symlink `markov` in it that points to `..` (your repo dir).
